### ISSUE TITLE
Bots should use items when they are pinged

### ISSUE THREAD

**Issue by NikolasTzimoulis** [NikolasTzimoulis/Couriers#20]

**Comment by DimasDSF** [comment]
Assuming you mean `NO_TARGET` items such as mek, greaves etc.
`ExecuteOrderFilter` `event.order_type == 27` (DOTA_UNIT_ORDER_PING_ABILITY) is something that comes to mind.
You will just need to make sure that the issuer is on the same team as the bot and then you can either call `CastAbilityNoTarget(handle ability, int playerIndex)` or fill a table and [`ExecuteOrderFromTable(handle handle_1)`](https://developer.valvesoftware.com/wiki/Dota_2_Workshop_Tools/Scripting/API/Global.ExecuteOrderFromTable).
The bots seem to fight the second one sometimes.

**Comment by NikolasTzimoulis** [comment]
@DimasDSF That's extremely useful. Thanks!

**Comment by NikolasTzimoulis** [comment]
@DimasDSF Just pushed an update that includes this feature, implemented based on your tips. Thanks.
