### ISSUE TITLE
Items with charges don't work correctly

### ISSUE THREAD

**Issue by NikolasTzimoulis** [NikolasTzimoulis/Couriers#23]
Items with more than one stack just turn into one stack after transferred from courier to heroes

**Comment by SanctusAnimus** [comment]
If i understanded correctly, item transfer is done by this part:
```lua
   	for _,hero in pairs(heroes) do 
   		if IsValidEntity(hero) and hero:IsRealHero() then 
			for itemSlot = 0, 11, 1 do 
				local item = hero:GetItemInSlot( itemSlot ) 
				if IsValidEntity(item) and item:GetPurchaser() ~= hero then 
					--print(item:GetName().." "..item:GetOwnerEntity():GetName())
					local itemname = item:GetName()
					item:RemoveSelf()
					hero:AddItem(CreateItem(itemname, hero, hero))
				end
			end	
   		end
	end
```
And here's the trick: Item charges are assigned to item, and when you recreate the item by it's name, you create a blank new one, with basic amount of charges. So, before removing old item, get it stack count, and if it's more then one, save it and set new item stack count to saved value.

Hope this will help you. GL!

**Comment by NikolasTzimoulis** [comment]
@SanctusAnimus you're absolutely right, this is exactly what I'm gonna do.
